description: "My eval"

prompts:
  - file://prompt.txt
  

providers:
  - "mistral:mistral-medium-latest"
  - "mistral:mistral-small-latest"
  - "groq:gemma2-9b-it"

tests:
  - vars:
      name: Bob
      question: Percentage of older adults who are experiencing frequent mental distress?
  - vars:
      name: Jane
      question: Percentage of older adults who report having lost 5 or fewer teeth due to decay or gum disease?
  - vars:
      name: Ben
      question: Percentage of older adults who reported subjective cognitive decline or memory loss that interferes with their ability to engage in social activities or household chores?
  - vars:
      name: Dave
      question: Percentage of older adults who reported subjective cognitive decline or memory loss that is happening more often or is getting worse in the preceding 12 months?